"use client";
import { useEffect, useState } from "react";
import { CalendarDays, CheckCircle2, LogOut, RefreshCw, Trash2 } from "lucide-react";

type Booking={id:string;booking_date:string;court:string;start_time:string;customer_name:string;phone:string;email:string;players:number;paddle_rental:number;ball_rental:number;training_balls:number;amount:number;payment_reference:string|null;status:string;created_at:number};
function displayTimeRange(value:string){const selected=value.split("|");if(selected.length===1)return value;const times=["6:00 AM","7:00 AM","8:00 AM","9:00 AM","10:00 AM","11:00 AM","12:00 PM","1:00 PM","2:00 PM","3:00 PM","4:00 PM","5:00 PM","6:00 PM","7:00 PM","8:00 PM","9:00 PM","10:00 PM","11:00 PM"];const endHour=(6+times.indexOf(selected[0])+selected.length)%24;return `${selected[0]}–${endHour%12||12}:00 ${endHour<12?"AM":"PM"} (${selected.length} hours)`}

export default function AdminDashboard({email}:{email:string}){
 const[bookings,setBookings]=useState<Booking[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/admin/bookings",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setBookings(d.bookings)}catch(e){setError(e instanceof Error?e.message:"Bookings could not be loaded.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const update=async(id:string,body:Record<string,string>)=>{setBusy(id);setError("");setNotice("");try{const r=await fetch("/api/admin/bookings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...body})});const d=await r.json();if(!r.ok)throw new Error(d.error);if(body.action==="verify")setNotice(d.emailSent?"Payment verified — confirmation email sent to the customer.":"Payment verified, but the confirmation email could not be sent.");await load()}catch(e){setError(e instanceof Error?e.message:"Booking could not be updated.")}finally{setBusy("")}};
 const reschedule=(booking:Booking,event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);update(booking.id,{action:"reschedule",bookingDate:String(f.get("bookingDate")),court:String(f.get("court")),startTime:String(f.get("startTime"))})};
 return <main className="admin-page"><header className="admin-header"><div><img src="/dink-lounge-logo-transparent.webp" alt="Dink Lounge logo"/><div><strong>Booking management</strong><small>{email}</small></div></div><a href="/cdn-cgi/access/logout" target="_top"><LogOut/> Sign out</a></header><section className="admin-content"><div className="admin-title"><div><p>PRIVATE DASHBOARD</p><h1>Court bookings</h1><span>Verify payments, cancel reservations, or move customers to another available slot.</span></div><button onClick={load}><RefreshCw/> Refresh</button></div>{error&&<p className="admin-error">{error}</p>}{notice&&<p className="admin-success">{notice}</p>}{loading?<p className="admin-empty">Loading bookings…</p>:bookings.length===0?<p className="admin-empty">No bookings yet.</p>:<div className="booking-list">{bookings.map(b=><article className="admin-booking" key={b.id}><div className="booking-summary"><div><span className={`status ${b.status}`}>{b.status.replace("_"," ")}</span><h2>{b.customer_name}</h2><p><CalendarDays/> {b.booking_date} • {displayTimeRange(b.start_time)} • {b.court}</p></div><strong>₱{b.amount}</strong></div><div className="booking-details"><span><small>PHONE</small>{b.phone}</span><span><small>EMAIL</small>{b.email}</span><span><small>PLAYERS</small>{b.players}</span><span><small>PAYMENT PROOF</small>{b.status==="payment_submitted"||b.status==="paid"?"Receipt sent via Facebook":"Awaiting receipt"}</span></div><div className="booking-actions">{b.status!=="paid"&&<button className="verify" disabled={busy===b.id} onClick={()=>update(b.id,{action:"verify"})}><CheckCircle2/> Verify payment</button>}<form onSubmit={e=>reschedule(b,e)}><input name="bookingDate" type="date" defaultValue={b.booking_date} required/><select name="court" defaultValue={b.court}><option>Court 1</option><option>Court 2</option></select><select name="startTime" defaultValue={b.start_time.split("|")[0]}>{times.map(t=><option key={t}>{t}</option>)}</select><button disabled={busy===b.id}>Reschedule</button></form><button className="cancel" disabled={busy===b.id} onClick={()=>{if(confirm("Cancel this booking and reopen the slot?"))update(b.id,{action:"cancel"})}}><Trash2/> Cancel</button></div></article>)}</div>}</section></main>
}
